### ISSUE TITLE
Oncoder online Mock Test_1회

### ISSUE THREAD

**Issue by HojinJava** [pro00er/algorithmSolution#34]
### 풀이할 문제 링크
- 문제 비공개로 링크 적지 않음

### 작업한 거
- [x] issue title 형식에 맞는가? (문제플랫폼명_문제카테고리명_문제이름 / e.g. codility_Lesson06_sorting_heyheyhey)
- [ ] 풀이 PR
- [ ] hojinjava꺼 코드리뷰
- [ ] ohahohah꺼 코드리뷰
- [ ] kimsunoh꺼 코드리뷰

**Comment by kimsunoh** [comment]
제곱근, 소수를 구하는 문제가 알고리즘을 학습할 때, 연산자 연습을 하기위한 시그니처 문제인거 같아요 (2번문제)

**Comment by ohahohah** [comment]
rename method 참고여. 추천 동사는 지금 어딨는지 모르겠네요. cleancode 나 다른 책 찾아서 공유할게요
https://refactoring.com/catalog/renameMethod.html
